[tool.poetry]
name = "download-manager"
version = "0.1.0"
description = "A download manager built with PyQt6 and pySmartDL"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
PyQt6 = "^6.5.0"
pySmartDL = "1.3.4"
PyQt6-Qt6 = "^6.5.0"
PyQt6-sip = "^13.5.0"
PyQt6-WebEngine = "^6.5.0"
PyQt6-WebEngine-Qt6 = "^6.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
