[tool.poetry]
name = "pasargadae"
version = "0.1.0"
description = ""
authors = ["HK <hamedk@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
PySide = "^6.8.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
